# Generated by Django 4.2 on 2023-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitedaddress",
            name="building_id",
            field=models.IntegerField(),
        ),
    ]
