# Generated by Django 4.1.7 on 2023-09-02 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_visitedaddress_building_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitedaddress",
            old_name="building_id",
            new_name="nycdb_building_id",
        ),
    ]
