# Generated by Django 4.1.7 on 2023-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_visitedaddress_building_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitedaddress",
            name="nycdb_building_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
