# Generated by Django 4.1.7 on 2023-09-02 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_visitedaddress_nycdb_building_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitedaddress",
            name="nycdb_building_id",
        ),
    ]
