# Generated by Django 4.2 on 2024-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_visitedaddress_nycdb_building_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitedaddress",
            name="owners_not_interested",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
